version: "3.8"

services:
  
  api:
    build: .
    container_name: "auth-rest-api"
    environment:
      ACCESS_SECRET: "unchangeableaceesssecret"
      REFRESH_SECRET: "unchangeablerefreshsecret"
    ports:
      - "8080:8080"
    networks:
      - fullstack

networks:
  fullstack:
    driver: bridge
